//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDesk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusHistory
    {
        public int HistoryID { get; set; }
        public int RequestID { get; set; }
        public int StatusID { get; set; }
        public int ChangedBy { get; set; }
        public System.DateTime ChangedAt { get; set; }
        public string Comment { get; set; }
        public Nullable<int> OldStatusID { get; set; }
    
        public virtual Requests Requests { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
        public virtual Statuses Statuses1 { get; set; }
    }
}
